[package]
name = "Talent_Token"
version = "1.0.0"
authors = []

[addresses]
Talent_token = 'a55e19265f2eb36db1aa5272a8ddfcaf2b17afd4c4662e63858df15867c7f88d'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
